baseURL: "https://praimeteam.llc"
languageCode: "en-us"
# theme: "up-business-theme" # based on, with additional modifications


# Site banner
title: "PRAIME Team LLC"

# googleAnalytics: ""

summaryLength: 20


# Bottom
params:
  title: "PRAIME Team LLC"
  description: "We provide consulting services on Artificial Intelligence (AI), Machine Learning (ML), Recommendation Systems, Search, Media, Streaming, e-Commerce, and Advertising."
  
  # Images of the posts
  images: 
    - "images/Clack-prew-Product-20Launch.jpg"
    - "images/hero-image.png"

  # Favicon in tab
  logo: "images/arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    # dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"
    linkedin: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2024 PRAIME Team LLC All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/about"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/about"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
